# Generated by Django 5.2.7 on 2025-11-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('divisa_pref', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('COP', 'COP')], default='COP', max_length=3)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ing', 'ing'), ('eg', 'eg')], max_length=3)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.usuario')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Bolsillo',
            fields=[
                ('bolsillo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.usuario')),
            ],
            options={
                'db_table': 'bolsillo',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('transferencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('a_bolsillo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_destino', to='finances.bolsillo')),
                ('de_bolsillo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_origen', to='finances.bolsillo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finances.usuario')),
            ],
            options={
                'db_table': 'transferencia',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ing', 'ing'), ('eg', 'eg')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('bolsillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.bolsillo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.usuario')),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('bolsillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.bolsillo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.grupo')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transferencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.usuario')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('egreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('bolsillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.bolsillo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.grupo')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transferencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.usuario')),
            ],
            options={
                'db_table': 'egreso',
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('miembro', 'miembro')], default='miembro', max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.usuario')),
            ],
            options={
                'db_table': 'usuario_grupo',
            },
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('de_bolsillo', models.F('a_bolsillo')), _negated=True), name='chk_transferencia_bolsillos_diff'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('monto_origen__gt', 0), ('monto_destino__gt', 0)), name='chk_transferencia_montos_pos'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('grupo__isnull', True), _connector='XOR'), name='chk_movimiento_owner'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_movimiento_monto'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('grupo__isnull', True), _connector='XOR'), name='chk_ingreso_owner'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_ingreso_monto'),
        ),
        migrations.AddConstraint(
            model_name='egreso',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('grupo__isnull', True), _connector='XOR'), name='chk_egreso_owner'),
        ),
        migrations.AddConstraint(
            model_name='egreso',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_egreso_monto'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('grupo__isnull', True), _connector='XOR'), name='chk_categoria_owner'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre', 'tipo'), name='uk_cat_u_nombre_tipo'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre', 'tipo'), name='uk_cat_g_nombre_tipo'),
        ),
        migrations.AddConstraint(
            model_name='bolsillo',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('grupo__isnull', True), _connector='XOR'), name='chk_bolsillo_owner'),
        ),
        migrations.AddConstraint(
            model_name='bolsillo',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='uk_bolsillo_usuario_nombre'),
        ),
        migrations.AddConstraint(
            model_name='bolsillo',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='uk_bolsillo_grupo_nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariogrupo',
            unique_together={('usuario', 'grupo')},
        ),
    ]
