# Generated by Django 5.2.7 on 2025-11-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_categoria_color'),
        ('finances', '0004_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
    ]
