# Generated by Django 5.2.7 on 2025-11-07 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_add_bolsillo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
