# Generated by Django 5.2.7 on 2025-11-08 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_grupo_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('aportacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bolsillo_grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aportaciones_destino', to='finances.bolsillo')),
                ('bolsillo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aportaciones_origen', to='finances.bolsillo')),
                ('egreso_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportacion_egreso', to='finances.egreso')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finances.grupo')),
                ('ingreso_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportacion_ingreso', to='finances.ingreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aportacion',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_aportacion_monto')],
            },
        ),
    ]
