# Generated by Django 5.2.7 on 2025-11-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_aportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
